# Configurações de conexão com o banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://projeto-integrador.cbouamm0wbt7.us-east-1.rds.amazonaws.com:5432/dbProjeto
spring.datasource.username=daniel
spring.datasource.password=Bitcoin2024
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Configurações de logging
logging.level.root=INFO
logging.level.org.hibernate=DEBUG

# Configurações adicionais (opcional)
spring.jpa.show-sql=true  # Para exibir as consultas SQL no log
spring.jpa.properties.hibernate.format_sql=true  # Para formatar as consultas SQL
